apiVersion: v1
kind: Service
metadata:
  name: ticket-management-to-cluster-service
spec:
  type: LoadBalancer
  selector:
    app: ticket-management-to-cluster
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080